### ISSUE TITLE
As a user I can view the current temperature from my current location

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/Umbrella#1]
When the app is first launched, display the current temperature based on the user's location.

### Task List
 - [x] Create UI
 - [x] Grab user's location
 - [x] Fetch weather data
 - [x] Display current tempature to user

### Acceptance Criteria
- [x] Current temperature in Fahrenheit is displayed to the user
