### ISSUE TITLE
As a user I can view the forecast for the rest of the day

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/Umbrella#2]
display the hour by hour forecast for the rest of the day to the user.

### Task List
 - [x] Create UI
 - [x] Setup recycler view
 - [x] retrieve images, and times for weather item

### Acceptance Criteria
- [x] Hour by hour forecast for the day is displayed

**Comment by Kennygunderman** [comment]
Also included: highlighting high/low temps
