### ISSUE TITLE
App color changes based on temperature

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/Umbrella#3]
When the temperature falls below 60 degrees Fahrenheit, change the app to a cool blue color.

### Task List
 - [x] Logic to change color when tempature drops
 - [ ] Write applicable tests

### Acceptance Criteria
- [x] App color changes when temp is below 60 degrees.
