### ISSUE TITLE
As a user I can Enter a ZIP code to retrieve a daily forecast

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/Umbrella#4]
we want to be able to change the location of the forecast based on a ZIP code provided from the user.

### Task List
 - [x] Create settings page
 - [x] Observe ZIP code, and update weather when zip is changed
 - [ ] Write applicable tests

### Acceptance Criteria
- [x] Forecast changes to location of the entered ZIP code

**Comment by Kennygunderman** [comment]
skipping tests to save time
